# Generated by Django 3.2.8 on 2021-11-09 13:37

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='approval_doc',
            field=models.FileField(upload_to=accounts.models.seller_doc_path, validators=[accounts.models.file_size, django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
