# Generated by Django 3.2.8 on 2021-11-08 14:22

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_1',
            field=models.ImageField(default=None, upload_to=ecommerce.models.product_image_path1),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(default=None, upload_to=ecommerce.models.product_image_path2),
        ),
    ]
