# Generated by Django 3.2.8 on 2021-11-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20211108_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_delivery_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_quantity_available',
        ),
    ]
