# Generated by Django 3.2.8 on 2021-11-08 15:26

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20211108_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=None, upload_to=ecommerce.models.category_image_path),
        ),
    ]
