# Generated by Django 3.2.8 on 2021-11-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shipping_details',
            name='delivery_address',
            field=models.TextField(max_length=500),
        ),
    ]
